name: build crx
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: React app build
        run: npm run build
      
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'build'
          zipFilePath: 'extension.crx'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: extension-crx
          path: extension.crx
          retention-days: 5
